### PR TITLE
Added missing & matching Spawn Eggs

### PR DESCRIPTION
**Pull request by ZeitHeld**
Added some Missing translations (such as biomes or Journal Menu name) Changed the names of the Spawn Eggs to match Vanilla Added a few empty lines (for better translation sight)

### CODE REVIEW

**Comment by Wehavecookies56** [comment]
The en_us is generated so any edits get overwritten whenever the datagen is run so they should be added [here](https://github.com/Wehavecookies56/Kingdom-Keys/blob/master/src/main/java/online/kingdomkeys/kingdomkeys/datagen/init/LanguageENUS.java)

**Comment by ZeitHeld** [comment]
oh yeah, I forgot about that
Will fix that

**Comment by ZeitHeld** [comment]
I did update it, am just a bit unsure if that is correct entirely in code, but tried to follow it along reading the source

And question, should I add the german translation similarily? or would the lang be enough?

**Comment by Wehavecookies56** [comment]
You could do if you want but it is quite a lot of effort to do so, so just the lang file is fine.

**Pull request merged**
