### PR TITLE
kingdom keys jp lang

### PR DESCRIPTION
**Pull request by roxchan6668**

### CODE REVIEW

**Comment by roxchan6668** [comment]
jp lang

**Comment by Wehavecookies56** [comment]
Nice, could you move it from src/generated/resources/assets/kingdomkeys/lang to src/main/resources/assets/kingdomkeys/lang?

**Review by Wehavecookies56 — CHANGES_REQUESTED** [review]
needs moving from src/generated/resources/assets/kingdomkeys/lang to src/main/resources/assets/kingdomkeys/lang as it's not generated with datagen

**Comment by roxchan6668** [comment]
OK

**Pull request merged**
